# Generated by Django 3.2.25 on 2024-07-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=21, verbose_name='Название магазина')),
                ('name', models.CharField(max_length=21, verbose_name='Имя сотрудника')),
                ('surname', models.CharField(max_length=21, verbose_name='Фамилия сотрудника')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организация',
            },
        ),
        migrations.DeleteModel(
            name='Shop_brand',
        ),
    ]
