# Generated by Django 3.2.25 on 2024-07-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='title',
        ),
    ]
