# Generated by Django 3.2.25 on 2024-07-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0002_remove_employees_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
